apiVersion: v1
kind: Service
metadata:
  name: app-python-service
  namespace: lesson-1
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Local
  selector:
    app: app-python
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30800
