apiVersion: v1
kind: Service
metadata:
  name: {{ include "bfa.fullname" . }}
  labels:
    {{- include "bfa.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30800
  selector:
    {{- include "bfa.selectorLabels" . | nindent 4 }}
