apiVersion: v1
kind: Service
metadata:
  name: app-vuejs-service
  namespace: lesson-1
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: true
  selector:
    app: app-vuejs
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
